### ISSUE TITLE
Post "Parallel benchmarking with OpenML and mlr" needs review

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr-web#1]
I cannot get this post rendered locally, it always exceeds the RAM and SWAP of my machine. For now I set `eval = FALSE` for all chunks.

When restricting the number of cores to 2 it works. However, I am then stuck at 

```r
results0 = reduceResultsDataTable()
```

which returns an empty list.

@HeidiSeibold Could you take a look here? We just switched from Jekyll to Blogdown + HUGO. Things should be easier now. Would be great if we can the post rendering again!

**Comment by HeidiSeibold** [comment]
I have no capacity for this at them moment, sorry. You need to have an `apikey` set for uploading stuff to OpenML. You can test if it works using `testJob(1)`. 

Another option: Can't you get the outputs/images from the old repo and not render it from scratch? This would also avoid cluttering the OpenML server.

**Comment by HeidiSeibold** [comment]
I'm really sorry I can't be of any more help here atm! Maybe @mllg has some time?

**Comment by pat-s** [comment]
Hi Heidi,

thanks for the quick response! No worries about the time issue.
I'll see what I can do with the hints - a read-only post would also be sufficient. 
Its not urgent since the post is already a bit old and not so many people will read it in the next time. Nevertheless we should try to keep the posts working ofc :+1:

**Comment by berndbischl** [comment]
either make it read only or remove it if it blocks the functioning of the whole blog
we can always come back to this later
