### ISSUE TITLE
Bug Report: Page Broken

### ISSUE THREAD

**Issue by JiaxiangBU** [mlr-org/mlr-web#14]
In this post, https://github.com/mlr-org/mlr-web/blob/dfb06677116aff69d7729b7455ac136f1be7b6f8/content/docs/2016-08-23-How-to-win-a-drone-in-20-lines-of-R-code.Rmd
The link related to partial dependence cannot be accessed. https://mlr-org.github.io/exploring-learner-predictions-with-partial-dependence/

**Comment by pat-s** [comment]
Thanks. This is due to the fact that the post does not render anymore and is not served on the site currently. See https://github.com/mlr-org/mlr-web/issues/2

You can find the source in the repo here.
