### ISSUE TITLE
Add disqus

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr-web#3]
To enable commenting on posts.

**Comment by jakob-r** [comment]
We had disqus in the old blog. So we should probably use the same id. Maybe the comments will survive?

**Comment by pat-s** [comment]
@jakob-r 	Setting disqusShortname = "mlr-org-blog" in `config.toml` doesn't simply do the job. Can you take a look in the account or share the credentials with me?

**Comment by pat-s** [comment]
Now using utter.ances as disqus is questionable with respect to privacy.
